### ISSUE TITLE
Уточнение постановки задачи

### ISSUE THREAD

**Issue by Mazdaywik** [bmstu-iu9/utp2017-3-forth#1]
Необходимо сформулировать общее представление о проекте — синтаксис используемого языка программирования, внешний вид пошагового интерпретатора-отладчика, интерфейс выбора тем оформления. Полученное представление следует описать в README.md в виде одного или нескольких абзацев. После этого данную задачу можно закрывать.

**Comment by TSARukyanGT** [comment]
Еще не до конца написан файл Readme, но все таки задачу я закрою, т.к. основы там есть
