### ISSUE TITLE
Создание словаря переменных и работа с ним (интерпретатор).

### ISSUE THREAD

**Issue by TSARukyanGT** [bmstu-iu9/utp2017-3-forth#11]
Создание словаря констант и переменных (пользовательских) с возможностью изменять их.

**Comment by opium-poppy** [comment]
[Задача выполнена](https://github.com/bmstu-iu9/utp2017-3-forth/pull/13)

**Comment by opium-poppy** [comment]
[Исправлено](https://github.com/bmstu-iu9/utp2017-3-forth/pull/50)
