### ISSUE TITLE
Создание словаря переменных и работа с ним (отладчик).

### ISSUE THREAD

**Issue by TSARukyanGT** [bmstu-iu9/utp2017-3-forth#14]
Создание словаря констант и переменных (пользовательских) с возможностью изменять их.

**Comment by opium-poppy** [comment]
[Задача выполнена](https://github.com/bmstu-iu9/utp2017-3-forth/pull/15)

**Comment by opium-poppy** [comment]
[Исправлено](https://github.com/bmstu-iu9/utp2017-3-forth/pull/50)
