### ISSUE TITLE
Разработка архитектуры проекта и распределение ролей

### ISSUE THREAD

**Issue by Mazdaywik** [bmstu-iu9/utp2017-3-forth#2]
Требуется разработать архитектуру отладчика:
* выбрать подходы и технологии, которые будут использоваться при разработке, а именно паттерны проектирования;
* определить, из каких крупных компонентов будет состоять решение;
* распределить обязанности участников между различными компонентами и различными видами деятельности, создав на каждую подзадачу «issue» и назначив её на участника.

**Comment by TSARukyanGT** [comment]
все задачи (вроде бы совсем все) распределены
