### ISSUE TITLE
Исправление файлов ресурсов

### ISSUE THREAD

**Issue by TSARukyanGT** [bmstu-iu9/utp2017-3-forth#25]
Исправление файлов ресурсов для дизайнов "Литература" и "Природа"

**Comment by IgorZobnev** [comment]
Исправлены файлы ресурсов. ["Литература"](https://github.com/bmstu-iu9/utp2017-3-forth/pull/29) и ["Природа"](https://github.com/bmstu-iu9/utp2017-3-forth/pull/30) перезагружены, задание выполнено.
