### ISSUE TITLE
Один из этих двух файлов явно лишний

### ISSUE THREAD

**Issue by Mazdaywik** [bmstu-iu9/utp2017-3-forth#37]
Один из этих двух файлов явно лишний:

* https://github.com/bmstu-iu9/utp2017-3-forth/blob/154d6c3801af0e8bf267c427a56bc5ea304c290b/Literature/Resources/Name%20of%20a%20project.png
* https://github.com/bmstu-iu9/utp2017-3-forth/blob/154d6c3801af0e8bf267c427a56bc5ea304c290b/Literature/Resources/name%20of%20a%20project.png

Они оба имеют имена, различающиеся лишь регистром, из-за чего нельзя корректно скачать репозитории под Windows (и, скорее всего, под macOS).

**Comment by IgorZobnev** [comment]
Не волнуйтесь, эти файлы нам не понадобятся, как оказалось. Это вообще я сделал для защиты от плагиата, но ребята сказали, что вся информация будет доступна и без этой картинки.

**Comment by TSARukyanGT** [comment]
[Лишний файл удален](https://github.com/bmstu-iu9/utp2017-3-forth/pull/39)

**Comment by Mazdaywik** [comment]
Мне не особо важно, понадобятся файлы или нет.

Просто дело в том, что в проекте было два файла, имена которых различались регистром символов. С точки зрения файловых систем Windows и macOS, это один и тот же файл. Поэтому когда Git распаковывает репозитории, он сначала выписывает один, потом поверх него записывает другой файл и отображает первый из них как изменённый.
