### ISSUE TITLE
Изменение размеров фотографий фона кнопок "переменные" и "функции"

### ISSUE THREAD

**Issue by KabudoWiseMan** [bmstu-iu9/utp2017-3-forth#51]
Нужно загрузить новые фотографии фона кнопок "переменные" и "функции" для всех тем

**Comment by TSARukyanGT** [comment]
а что в них изменить-то надо?

**Comment by KabudoWiseMan** [comment]
Игорь знает, надо размер кнопок со 150 на 230 поменять

**Comment by TSARukyanGT** [comment]
270 наверно? И исходники разве остались?

**Comment by KabudoWiseMan** [comment]
Если я написал 230, значит 230. Я уже всё сделал, Игорю надо только фотки, которые я ему скинул, загрузить вместо старых

**Comment by IgorZobnev** [comment]
Изменены файлы ресурсов. [Задание выполнено.](https://github.com/bmstu-iu9/utp2017-3-forth/pull/58)
