### ISSUE TITLE
Тесты

### ISSUE THREAD

**Issue by TSARukyanGT** [bmstu-iu9/utp2017-3-forth#56]
Написание тестовых программ

**Comment by TSARukyanGT** [comment]
ВНИМАНИЕ! Добавляйте в обычном порядке ссылки на свои pull request'ы, но не закрывайте задачу! Задачу требуется закрыть после добавления всех тестов всеми участниками задачи.

**Comment by koshelevandrey** [comment]
[Добавлены тесты](https://github.com/bmstu-iu9/utp2017-3-forth/pull/54) [(fix)](https://github.com/bmstu-iu9/utp2017-3-forth/pull/55)

**Comment by opium-poppy** [comment]
[Добавлены тесты на drop, drop-all, dup, rot](https://github.com/bmstu-iu9/utp2017-3-forth/pull/81)

**Comment by IgorZobnev** [comment]
[Добавлены тесты для +, swap, over, if-endif.](https://github.com/bmstu-iu9/utp2017-3-forth/pull/82)

**Comment by Mazdaywik** [comment]
Если в комментарии к pull-request’у просто упомянуть эту задачу — написать «#56», то ссылка сама добавится сюда (см. выше про #81). Но, если вы считаете нужным явно добавлять ссылки в виде комментариев — добавляйте. Тоже нормально.
