### ISSUE TITLE
Не удаётся запустить отладчик

### ISSUE THREAD

**Issue by Mazdaywik** [bmstu-iu9/utp2017-3-forth#59]
Вместе с Александром Вячеславовичем открыли файл `main.html`, в нём у нас нормально работала только смена тем и открытие окна отладчика. Остальные кнопки (включая кнопки в окне отладчика) не работали. Пробовали в браузерах Edge и Chrome.

![forth](https://user-images.githubusercontent.com/1309859/29778459-2067d6d2-8c18-11e7-84a6-b19df0b45ba1.PNG)

Что мы делаем не так?

**Comment by KabudoWiseMan** [comment]
Всё правильно. Сейчас работает только кнопка смены стилей и кнопка выхода из окна отладчика. Остальными кнопками и полями ввода занимаются другие ребята, как только они допишут код, я вставлю его на сайт. Ответил я, так как самим сайтом занимаюсь я

**Comment by TSARukyanGT** [comment]
Дополню ответ Севы - для остальных функций программы в данный момент в репозитории лежат отдельные html файлы:
для интерпретатора (с добавленным текстовым полем Ace) - Run.html
для отладчика (с начальными текстовыми полями) - Debug.html
для вывода словарей переменных/функций - OutputTest.html
для сохранения и загрузки текстовых файлов - save-as.html
для сохранения и выбора версий текста (по сути - буфер обмена для состояний программы) - transitional_versions.html

**Comment by TSARukyanGT** [comment]
Скажите, Вы уже проверяли нашу программу? Если нет, то когда будете это делать?

**Comment by TSARukyanGT** [comment]
На данный момент все вроде бы сделано. Эту задачу я закрывать сам не буду - возможно она Вам еще понадобится

**Comment by TSARukyanGT** [comment]
Видимо, задача нужна уже не будет
