### ISSUE TITLE
Возвращение файлов

### ISSUE THREAD

**Issue by TSARukyanGT** [bmstu-iu9/utp2017-3-forth#60]
В срочном и обязательном порядке необходимо вернуть в репозиторий файлы ШАБЛОНОВ всех тем! Они должны быть помещены в папку templates и внутри нее в персональную папку темы. Шаблоны - для начальной страницы и для отладчика. И в следующий раз (уже не просьба, а требование!!!) - согласуй все изменения! Не удаляй файлы, если просто считаешь сам, что "они не понадобятся", тем более если их ПРОСИЛИ (а я лично просил) НЕ УДАЛЯТЬ!!!

**Comment by Mazdaywik** [comment]
Можно же просто взять и ревёртнуть коммиты. Цитирую пример из man’а.
```
git revert -n master~5..master~2
```
> Revert the changes done by commits from the fifth last commit in master (included) to the third last commit in master (included), but do not create any commit with the reverted changes. The revert only modifies the working tree and the index.

«Удалённые» файлы никуда не потерялись. Они берутся и извлекаются из истории. Другой вариант к ним вернуться — переключиться на коммит, где они были
```
git checkout 123abcd
```
скопировать файлы куда-то в другую папку
```
copy *.png c:\save-pictures
```
вернуться обратно на свою ветку
```
git checkout my-branch
```
и поместить файлы в репозитории
```
move c:\save-pictures\*.png .
git add *.png
git commit -m "Вернул файлы из истории"
```

**Comment by Mazdaywik** [comment]
Файлы в Git в нормальном режиме работы никуда не теряются и не перезатираются. Они сохраняются в истории, и чтобы вернуться назад, достаточно ввести одну простую команду:
```
git checkout abc1234
```
Номер коммита можно узнать, если, например, просмотреть репозитории через Gitk. Чтобы его открыть, нужно ввести команду
```
gitk --all &
```
и потом найти в дереве коммитов интересующую фиксацию.

Другое дело, если перезаписывается история. Но, во-первых, я вам этих команд на лекции не давал. Во-вторых, ваши репозитории по УТП настроены на GitHub так, что сервер просто не даст перезаписать ветку `master`. Если коммит попал в ветку `master`, то он оттуда уже никуда не денется. И файлы, которые в нём были, репозиторий будет помнить всегда. И к ним всегда можно будет вернуться.

**Comment by TSARukyanGT** [comment]
"ревёртнуть коммиты" - то есть повторить их? Это будет как повтор того коммита? Если да - то в данном случае вариант не подошел бы, потому что файлы загружались одним коммитом (для каждой темы). Загрузить файл заново я, собственно, и попросил. Но вопрос в другом - пока программа не написана полностью (в черновом варианте), разве есть смысл убирать файлы, которые используются/использовались? Пока не будет утверждено, что файлы окончательно больше не нужны?

**Comment by TSARukyanGT** [comment]
В данном конкретном случае шаблоны понадобились Владу @StructDeStruct чтобы настроить цвет подсветки кода редактора - и в нужный момент их не оказалось

**Comment by Mazdaywik** [comment]
Ревёртнуть коммиты — «обратить» их. Если есть коммит f7ea9ad5f15ec4a777bc81d5ee4b3d333a0b5b07, удаляющий файл `White vintage/Resources/output field.png`.

Если в командной строке ввести команду
```
git revert f7ea9ad
```
то будет создан новый коммит, который «обращает» действие f7ea9ad5f15ec4a777bc81d5ee4b3d333a0b5b07 — добавляет файл в репозиторий.

Команда
```
git revert @ -m 1
```
создаст коммит, отменяющий слияние с ветвью `Design` — в `master`’е окажется то, что было в нём до pull-request’а.

Впрочем, тоже самое можно сделать и через web-интерфейс:
![-](https://user-images.githubusercontent.com/1309859/29786931-a4cda600-8c35-11e7-9dd8-0e6920e8562d.PNG)
При нажатии на эту кнопку будет автоматически создана новая ветвь с коммитом, отменяющим последствия слияния, и автоматически будет открыт запрос на слияние этой ветви. Его, как обычно, надо будет заапрувить, прежде чем влить.

Проблема в этом случае будет в том, что будут отменены изменения следующих файлов:
```
images/literature/dic_func_background.png
images/literature/dictionary.png
images/literature/functions.png
images/matrix/dictionary.png
images/matrix/functions.png
images/nature/dictionary.png
images/nature/functions.png
images/ubuntu/dictionary.png
images/ubuntu/functions.png
images/white/dictionary.png
images/white/functions.png
```
поскольку в ветви `Design` они обновлялись.

**Comment by IgorZobnev** [comment]
Восстановлены файлы шаблонов всех тем. [Задание выполнено.](https://github.com/bmstu-iu9/utp2017-3-forth/pull/76)
