### ISSUE TITLE
Нужен совет

### ISSUE THREAD

**Issue by TSARukyanGT** [bmstu-iu9/utp2017-3-forth#67]
Скажите, пожалуйста, каким образом будет лучше сохранять файл (на компьютер пользователя)? (от этого зависит и загрузка из файла)
Вариант 1:
В текстовый файл записывается только содержимое поля ввода кода (поле ввода стека игнорируется), загрузка происходит как перенос текста в поле ввода кода. Плюс: простота реализации - ничего не нужно переделывать; минус: потеря всей информации о начальном стеке)
Вариант 2:
В текстовый файл записывается содержимое поля ввода кода, пропускаются 1-2 строки, после этого записывается содержимое начального стека (в том виде, в котором есть - голова...хвост). Плюс: информация о стеке сохраняется; минус: файл не получится загрузить обычным способом, понадобится функция "разбиения" на код и стек, что может осложняться написанием стека в несколько строк или добавлением пропусков между блоками кода.
Вариант 3:
В начало файла в обратном порядке (!) записывается начальный стек, затем записывается содержимое поля ввода кода. Загрузка производится только в поле ввода кода. Плюс: сохраненный файл можно без проблем загрузить; минус: теряется первоначальная структура кода, нужно писать алгоритм "переворачивания стека".
(пример "сохранения" для 3 варианта
```
//на странице
dup      //}ввод кода

5 9       //}ввод стека
//программа выдаст результат: 5 5 9
```
```
//в сохраненном файле
9 5
dup
//программа выдаст результат: 5 5 9)
```

**Comment by Mazdaywik** [comment]
Чтобы выделить участок кода, его нужно окружить знаками трёх обратных кавычек

    ```
    //на странице
    dup      //}ввод кода
    
    5 9       //}ввод стека
    //программа выдаст результат: 5 5 9
    ```

будет отображаться как:
```
//на странице
dup      //}ввод кода

5 9       //}ввод стека
//программа выдаст результат: 5 5 9
```

**Comment by TSARukyanGT** [comment]
Не знал, что в комментариях также поддерживается markdown, спасибо. Но что по поводу сохранения / загрузки?

**Comment by Mazdaywik** [comment]
Мне больше нравится третий вариант. Отдельной строкой в начале выделить заполнение стека, затем пропустить пустую строку и записать основной код.

С одной стороны это будет уже корректная программа на вашем диалекте Forth’а, с другой стороны — по пустой строке можно отделить заполнение стека и непосредственный код (и соответствующим образом заполнить участки экрана).

Загрузку такой программы можно интерпретировать и как исполнение кода до первой пустой строки, либо первого активного слова.

**Comment by TSARukyanGT** [comment]
Спасибо за совет, значит будем делать так.
