### ISSUE TITLE
Добавление кнопок сохранения в файл и открытия из файла

### ISSUE THREAD

**Issue by KabudoWiseMan** [bmstu-iu9/utp2017-3-forth#70]
Добавить кнопки сохранения в файл и открытия из файла

**Comment by TSARukyanGT** [comment]
С кнопками теперь все в порядке, можешь использовать этот код

**Comment by TSARukyanGT** [comment]
закрой задачу, как закончишь

**Comment by KabudoWiseMan** [comment]
Сделал https://github.com/bmstu-iu9/utp2017-3-forth/pull/98
