### ISSUE TITLE
Исправление масштабирования

### ISSUE THREAD

**Issue by TSARukyanGT** [bmstu-iu9/utp2017-3-forth#75]
Исправление масштабирования окон в отладке (фоны текстовых полей). Также замечен баг "удлинения" окон, если окно очень узкое (например, при включенном режиме разработчика в Chrome)
![image](https://user-images.githubusercontent.com/29797897/29794068-25cfef56-8c4f-11e7-8587-b3a0814330cf.png)

**Comment by TSARukyanGT** [comment]
и масштабирование
![image](https://user-images.githubusercontent.com/29797897/29794149-6fd4d562-8c4f-11e7-83d7-7c3d1f0aa710.png)

**Comment by KabudoWiseMan** [comment]
<img width="437" alt="2017-08-29 14 56 18" src="https://user-images.githubusercontent.com/25466945/29819657-461a33d6-8cca-11e7-9257-a8f9a67f5219.png">
У меня сейчас всё работает, попробуй ещё раз

**Comment by TSARukyanGT** [comment]
а масштабирование доделал? закрывать задачу?

**Comment by KabudoWiseMan** [comment]
Нет

**Comment by KabudoWiseMan** [comment]
Сделал https://github.com/bmstu-iu9/utp2017-3-forth/pull/91

**Comment by TSARukyanGT** [comment]
@StructDeStruct зайди сюда плз)
