### ISSUE TITLE
Создать css класс "break_point" и подключить скрипт

### ISSUE THREAD

**Issue by StructDeStruct** [bmstu-iu9/utp2017-3-forth#83]
1) В нем должно быть определено единственное поле:
"position: absolute;"
2) подключить скрипт "/scripts/ace/break_point.js" к main.html

**Comment by StructDeStruct** [comment]
Прошу сделать это тебя, Сев, чтобы не возникло конфликта версий при слиянии.

**Comment by KabudoWiseMan** [comment]
Сделал https://github.com/bmstu-iu9/utp2017-3-forth/pull/98
